version: '3.3'
services:

  db:
    container_name: foodgram_database
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: foodgram_backend
    image: kkhitalenko/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: foodgram_frontend
    image: kkhitalenko/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend


volumes:
  database:
  static_value:
  media_value:
