# Generated by Django 3.2.19 on 2023-06-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'verbose_name': 'Количество ингридиента в рецепте', 'verbose_name_plural': 'Количество ингридиента в рецепте'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
    ]
